# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitusr" do
  version "0.2.1"

  on_macos do
    on_intel do
      sha256 "e79c275f2f42cca864e9fdd0f38abb31f55676c8428bb5cf736ca14cb2a7cf01"
      url "https://github.com/northwang-lucky/gitusr/releases/download/v#{version}/gitusr_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "e9cb7b1bf8ed2b3366478a8dc949853ff91b8857991c6e0d1b01d9a7b545fc03"
      url "https://github.com/northwang-lucky/gitusr/releases/download/v#{version}/gitusr_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "67733c5008d7f87e449caaed046b11bc5ce8b37d60a9771389a4ded762b702c3"
      url "https://github.com/northwang-lucky/gitusr/releases/download/v#{version}/gitusr_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "1a4c1ace47b061a5a220d26e03ec9f8113fb9241b5ccb4accd21a16488e9fb0c"
      url "https://github.com/northwang-lucky/gitusr/releases/download/v#{version}/gitusr_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gitusr"
  desc "CLI tool for managing and switching between git user identities"
  homepage "https://github.com/northwang-lucky/gitusr"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitusr"

  # No zap stanza required

end
