# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitusr" do
  version "1.0.0"

  on_macos do
    on_intel do
      sha256 "55679157d0ef00062ed9573fa68380d56c1784a74c16481290d446255aa67143"
      url "https://github.com/northwang-lucky/gitusr/releases/download/v#{version}/gitusr_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "5de99f1633a8f67325addcfd1d00fafde94d1f62687106280d43bb63a698d2c7"
      url "https://github.com/northwang-lucky/gitusr/releases/download/v#{version}/gitusr_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "2a6e9bf262537298cdad951ad816b03ad9d4cd6f6db10cb04c5b8edf51c4480c"
      url "https://github.com/northwang-lucky/gitusr/releases/download/v#{version}/gitusr_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "ab1283ebaf8436458711903c07a779d59e4b880e4796dea8f797ecd9c0713a6e"
      url "https://github.com/northwang-lucky/gitusr/releases/download/v#{version}/gitusr_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gitusr"
  desc "CLI tool for managing and switching between git user identities"
  homepage "https://github.com/northwang-lucky/gitusr"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitusr"

  # No zap stanza required

end
