# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitusr" do
  version "0.2.0"

  on_macos do
    on_intel do
      sha256 "d16e3b0ae5fc9e228852717f6346a046e53c220a5cc40e6cf81936f297414ec8"
      url "https://github.com/northwang-lucky/gitusr/releases/download/v#{version}/gitusr_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "b9fec52c1c03881187f834615124df183af7786059db29c73e0a0292c708e8c4"
      url "https://github.com/northwang-lucky/gitusr/releases/download/v#{version}/gitusr_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "855cfd29ab575742a457201fb98bf66e0cbdc62e63fc5538e47d95bff98da2c6"
      url "https://github.com/northwang-lucky/gitusr/releases/download/v#{version}/gitusr_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "66408b301cb1f173ac05c0b91e2e476d92ec351a71b8d46bbfd33fd88175f7e5"
      url "https://github.com/northwang-lucky/gitusr/releases/download/v#{version}/gitusr_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gitusr"
  desc "CLI tool for managing and switching between git user identities"
  homepage "https://github.com/northwang-lucky/gitusr"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitusr"

  # No zap stanza required

end
