# This file was generated by GoReleaser. DO NOT EDIT.
cask "gitusr" do
  version "0.1.1"

  on_macos do
    on_intel do
      sha256 "01245c90c9161c519d62ac31ade66fc2acf101e512f5fb44d041b450a590cd03"
      url "https://github.com/northwang-lucky/gitusr/releases/download/v#{version}/gitusr_#{version}_darwin_amd64.tar.gz"
    end
    on_arm do
      sha256 "c238cdca99d7f32b828157f9f4b6d2f4b1ecfd37daadb1ba31c414e8d0fa314b"
      url "https://github.com/northwang-lucky/gitusr/releases/download/v#{version}/gitusr_#{version}_darwin_arm64.tar.gz"
    end
  end

  on_linux do
    on_intel do
      sha256 "695814792f7ddff90d5b012733289719a522f6e79ce2e4ca5e75d5daa93c3864"
      url "https://github.com/northwang-lucky/gitusr/releases/download/v#{version}/gitusr_#{version}_linux_amd64.tar.gz"
    end
    on_arm do
      sha256 "78520ce0440998bc6f9804ef4cf50338326bb89fb7413c1094e71c9d5c544231"
      url "https://github.com/northwang-lucky/gitusr/releases/download/v#{version}/gitusr_#{version}_linux_arm64.tar.gz"
    end
  end

  name "gitusr"
  desc "CLI tool for managing and switching between git user identities"
  homepage "https://github.com/northwang-lucky/gitusr"

  livecheck do
    skip "Auto-generated on release."
  end

  binary "gitusr"

  # No zap stanza required

end
