# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Gitusr < Formula
  desc "CLI tool for managing and switching between git user identities"
  homepage "https://github.com/northwang-lucky/gitusr"
  version "1.0.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/northwang-lucky/gitusr/releases/download/v1.0.1/gitusr_1.0.1_darwin_amd64.tar.gz"
      sha256 "234569a0b8ce5b5f7b9fd87c9037a73d2b7a0c928742218c55dbbf6b3f9f8f4a"

      define_method(:install) do
        bin.install "gitusr"
        bin.install_symlink "gitusr" => "gu"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/northwang-lucky/gitusr/releases/download/v1.0.1/gitusr_1.0.1_darwin_arm64.tar.gz"
      sha256 "557ea67f5146f895209d706e60f5d0b3cb8c8c7fc48e3f16bc6fb7395a3bd458"

      define_method(:install) do
        bin.install "gitusr"
        bin.install_symlink "gitusr" => "gu"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/northwang-lucky/gitusr/releases/download/v1.0.1/gitusr_1.0.1_linux_amd64.tar.gz"
      sha256 "c678b5ae54ba4387cfb9a170bd086e454bda628dad67f4565ed8ffab321631c2"
      define_method(:install) do
        bin.install "gitusr"
        bin.install_symlink "gitusr" => "gu"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/northwang-lucky/gitusr/releases/download/v1.0.1/gitusr_1.0.1_linux_arm64.tar.gz"
      sha256 "4107090e624aef1e50e4279ff328a234ed53514a24bc03e8b7381a02813efdb5"
      define_method(:install) do
        bin.install "gitusr"
        bin.install_symlink "gitusr" => "gu"
      end
    end
  end
end
