# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SshTunnelDaemon < Formula
  desc "CLI tool for managing SSH tunnels"
  homepage "https://github.com/northwang-lucky/ssh-tunnel-daemon"
  version "2.1.1"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/northwang-lucky/ssh_tunnel_daemon/releases/download/v2.1.1/ssh-tunnel-daemon_2.1.1_darwin_amd64.tar.gz"
      sha256 "fa50fc299a480a4cc24d234e2965b138b09928141842900df0786ac319c0d50e"

      define_method(:install) do
        bin.install "ssh-tunnel-daemon"
        bin.install_symlink "ssh-tunnel-daemon" => "sshtnl"
        bin.install_symlink "ssh-tunnel-daemon" => "s17n"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/northwang-lucky/ssh_tunnel_daemon/releases/download/v2.1.1/ssh-tunnel-daemon_2.1.1_darwin_arm64.tar.gz"
      sha256 "fa5b4887f130a598547b71c30b623cd3c025535f9ca69f1f4db3e19efe136e5b"

      define_method(:install) do
        bin.install "ssh-tunnel-daemon"
        bin.install_symlink "ssh-tunnel-daemon" => "sshtnl"
        bin.install_symlink "ssh-tunnel-daemon" => "s17n"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/northwang-lucky/ssh_tunnel_daemon/releases/download/v2.1.1/ssh-tunnel-daemon_2.1.1_linux_amd64.tar.gz"
      sha256 "a655ed72bfc94db8c399edf7bfa7d5d642c88a1c36d4a13d331422fb3ba67257"
      define_method(:install) do
        bin.install "ssh-tunnel-daemon"
        bin.install_symlink "ssh-tunnel-daemon" => "sshtnl"
        bin.install_symlink "ssh-tunnel-daemon" => "s17n"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/northwang-lucky/ssh_tunnel_daemon/releases/download/v2.1.1/ssh-tunnel-daemon_2.1.1_linux_arm64.tar.gz"
      sha256 "be088315e0909aa2fb88b12676b5a8b8ca07f338d4e941f68797849206004ffb"
      define_method(:install) do
        bin.install "ssh-tunnel-daemon"
        bin.install_symlink "ssh-tunnel-daemon" => "sshtnl"
        bin.install_symlink "ssh-tunnel-daemon" => "s17n"
      end
    end
  end
end
