# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SshTunnelDaemon < Formula
  desc "CLI tool for managing SSH tunnels"
  homepage "https://github.com/northwang-lucky/ssh-tunnel-daemon"
  version "2.1.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/northwang-lucky/ssh_tunnel_daemon/releases/download/v2.1.0/ssh-tunnel-daemon_2.1.0_darwin_amd64.tar.gz"
      sha256 "dc939ea8244b8c87f2ee24a7e9b57b4c9034e6048a663a4e12a1a06ddc3264c0"

      define_method(:install) do
        bin.install "ssh-tunnel-daemon"
        bin.install_symlink "ssh-tunnel-daemon" => "sshtnl"
        bin.install_symlink "ssh-tunnel-daemon" => "s17n"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/northwang-lucky/ssh_tunnel_daemon/releases/download/v2.1.0/ssh-tunnel-daemon_2.1.0_darwin_arm64.tar.gz"
      sha256 "3f4cf19f50d0af4d99faac02acf9dc0b6b73e3019b5711460348eeed3fc730f8"

      define_method(:install) do
        bin.install "ssh-tunnel-daemon"
        bin.install_symlink "ssh-tunnel-daemon" => "sshtnl"
        bin.install_symlink "ssh-tunnel-daemon" => "s17n"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/northwang-lucky/ssh_tunnel_daemon/releases/download/v2.1.0/ssh-tunnel-daemon_2.1.0_linux_amd64.tar.gz"
      sha256 "19fc55298d0b5f68c178163fc3bbf54bccd6f7a431ac2a243831b28da19724c9"
      define_method(:install) do
        bin.install "ssh-tunnel-daemon"
        bin.install_symlink "ssh-tunnel-daemon" => "sshtnl"
        bin.install_symlink "ssh-tunnel-daemon" => "s17n"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/northwang-lucky/ssh_tunnel_daemon/releases/download/v2.1.0/ssh-tunnel-daemon_2.1.0_linux_arm64.tar.gz"
      sha256 "bcd9ef122e6ed35841e1f7a43296864040a464dcf832219e4bfe3c33954ffa24"
      define_method(:install) do
        bin.install "ssh-tunnel-daemon"
        bin.install_symlink "ssh-tunnel-daemon" => "sshtnl"
        bin.install_symlink "ssh-tunnel-daemon" => "s17n"
      end
    end
  end
end
