# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class SshTunnelDaemon < Formula
  desc "CLI tool for managing SSH tunnels"
  homepage "https://github.com/northwang-lucky/ssh-tunnel-daemon"
  version "1.2.0"
  license "MIT"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/northwang-lucky/ssh_tunnel_daemon/releases/download/v1.2.0/ssh-tunnel-daemon_1.2.0_darwin_amd64.tar.gz"
      sha256 "3d688f458da6504485ffdd8716fd8100395a3edc464b4c29642bc2d3aadcd2fd"

      define_method(:install) do
        bin.install "ssh-tunnel-daemon"
        bin.install_symlink "ssh-tunnel-daemon" => "sshtnl"
        bin.install_symlink "ssh-tunnel-daemon" => "s17n"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/northwang-lucky/ssh_tunnel_daemon/releases/download/v1.2.0/ssh-tunnel-daemon_1.2.0_darwin_arm64.tar.gz"
      sha256 "0461dd9bdf414c4cd6b125aa3ad34c9a5594885def49f9df3247a8b7d4612abf"

      define_method(:install) do
        bin.install "ssh-tunnel-daemon"
        bin.install_symlink "ssh-tunnel-daemon" => "sshtnl"
        bin.install_symlink "ssh-tunnel-daemon" => "s17n"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/northwang-lucky/ssh_tunnel_daemon/releases/download/v1.2.0/ssh-tunnel-daemon_1.2.0_linux_amd64.tar.gz"
      sha256 "b2ee4bad05d41b9c5f24b3e246a4e4a8e4c6a7dfb40a814599f790dd5c8eb056"
      define_method(:install) do
        bin.install "ssh-tunnel-daemon"
        bin.install_symlink "ssh-tunnel-daemon" => "sshtnl"
        bin.install_symlink "ssh-tunnel-daemon" => "s17n"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/northwang-lucky/ssh_tunnel_daemon/releases/download/v1.2.0/ssh-tunnel-daemon_1.2.0_linux_arm64.tar.gz"
      sha256 "9b867b255a805ce7b877b3c6fce0e7611b6753669a88b4939a961adf4d5f8677"
      define_method(:install) do
        bin.install "ssh-tunnel-daemon"
        bin.install_symlink "ssh-tunnel-daemon" => "sshtnl"
        bin.install_symlink "ssh-tunnel-daemon" => "s17n"
      end
    end
  end
end
